trigger:
- master
- develop

pr:
  branches:
    include:
    - '*'

strategy:
  matrix:
    Cliqz:
      scheme: 'Cliqz'
      actions: 'build'
    Ghostery:
      scheme: 'Ghostery'
      actions: 'build'
    CliqzTests:
      scheme: 'Cliqz'
      actions: 'test'

pool:
  vmImage: 'macOS 10.14'

steps:
- bash: |
    sudo xcode-select --switch /Applications/Xcode_11.1.app
  displayName: 'Change XCode to 11.1'

- task: NodeTool@0
  displayName: 'Define Node to v10.17.0'
  inputs:
    versionSpec: '10.17.0'

- bash: |
    set -x
    npm i -g npm@6.5
    /usr/local/bin/npm ci
  displayName: 'Install Node modules'

- bash: |
    set -x
    npm run build-user-scripts
  displayName: Generate User Scripts

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.6'
    addToPath: true

- bash: |
    set -x
    gem install bundler:2.0.2 --force
    bundle install --retry=3
    bundle exec pod install
  displayName: 'Install CocoaPods'

- bash: bundle exec fastlane lint
  displayName: 'Lint'

- task: Xcode@5
  inputs:
    actions: '$(actions)'
    sdk: 'iphonesimulator'
    xcWorkspacePath: 'UserAgent.xcworkspace'
    scheme: '$(scheme)'
    packageApp: true
    configuration: 'CI'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11'
    publishJUnitResults: true
    args: '-derivedDataPath builds'

- bash: |
    brew tap wix/brew
    brew install applesimutils
  displayName: Install dependencies

- bash: |
    npm run test-detox
  displayName: e2e test

- task: PublishBuildArtifacts@1
  condition: or(succeeded(), failed())
  displayName: Publish e2e tests screenshots
  inputs:
    pathtoPublish: './artifacts'
    artifactName: 'Screenshots'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  condition: or(succeeded(), failed())
  displayName: Publish e2e tests screenshots
  inputs:
    pathtoPublish: './builds/Build/Products/CI-iphonesimulator/UserAgent.app'
    artifactName: 'App'
    publishLocation: 'Container'
